### ISSUE TITLE
Conflict between jmockit and jacoco

### ISSUE THREAD

**Issue by henri-tremblay** [jmockit/jmockit1#125]
Related to this issue https://github.com/jacoco/jacoco/issues/272

The problem is still happening in the latest versions of jacoco/jmockit

This project reproduces the issue: https://github.com/henri-tremblay/jacocomockit

When the line in the readme is executed, you will get this exception:
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)

jmockit 1.14 and jacoco 0.7.2.201409121644 is used

**Comment by rliesenfeld** [comment]
Thanks, Henry. This problem indeed occurs with the latest versions of JMockit and JaCoCo, although only when mocking an *interface* with a MockUp. It does not occur for classes, neither for @Mocked interfaces.

The root cause is that JaCoCo adds fields (ie, it "changes the schema") whenever it instruments a class for coverage, *and* it does that even for *dynamically generated* classes.

I wished JaCoCo would not add fields (since doing so is not necessary, as demonstrated by my own coverage tool which never changes the schema of an instrumented class), therefore avoiding issues like this which can also occur with other bytecode instrumentation tools. This would require significant internal changes to JaCoCo, though, so I doubt it will be done.

Fortunately, there is a simpler solution: JaCoCo can (and should) automatically exclude any generated class (which has no associated ".class" file). This can easily be determined in JaCoCo´s CoverageTransformer class, by checking the ProtectionDomain object it receives: "if (protectionDomain.getCodeSource().getLocation() == null) return null;".

Until then, this exclusion can be specified manually by the user, by adding the following to the "jacoco-maven-plugin" in the pom.xml file:

        <configuration>
          <excludes>
            <exclude>*$Impl_*</exclude>
          </excludes>
        </configuration>

("$Impl_" is the prefix used by JMockit when it generates a class implementing a mocked-up interface. Such a class gets a ProtectionDomain with no location, since it doesn't exist in the filesystem.)

**Comment by rliesenfeld** [comment]
Oh, another thing (not related to JaCoCo): the example pom.xml has the "junit" dependency *before* "jmockit". This prevents JMockit from getting properly initialized, unless "-javaagent:jmockit.jar" is used *or* "@RunWith(JMockit.class)" is applied to JUnit test classes. My recommendation is to simply put "jmockit" before "junit" in the runtime classpath, though.

**Comment by henri-tremblay** [comment]
Great. Thanks a lot for the explanation.

Which coverage tool are you using? I got from Clover to Cobertura to Jacoco which was the stable-er one.

About the pom: Yes. You are right. They were in the right order and I've flipped them to give it a try. And forgot to put them back. Thanks.

**Comment by rliesenfeld** [comment]
The JMockit project actually contains two tools, the mocking APIs (jmockit.jar), and a code coverage tool (jmockit-coverage.jar). This coverage tool uses java.lang.instrument in a similar way to JaCoCo. Its advantages are in more sophisticated coverage metrics and better usability, while its (current) disadvantages are that it lacks an Eclipse plugin (like EclEmma) and also a Sonar plugin (which should be created eventually, I hope).

**Comment by henri-tremblay** [comment]
Ok. The Sonar plugin is a must :-)

**Comment by andrioli** [comment]
I guess that JaCoCo adds a fields in each instrumented class due to performance. Without the field each method call will need another call to a JaCoCo's runtime method that is synchronized.

**Comment by rliesenfeld** [comment]
Access to the field will have to be synchronized anyway, since multiple threads can be executing the same of line of code concurrently. In any case, whenever I tried to measure and compare runtime performance between JMockit Coverage and JaCoCo, I couldn't see any noticeable difference. In the end, most of the time goes into HTML report generation, not into bytecode instrumentation or data collection.

**Comment by andrioli** [comment]
I could be wrong, but I don't think that the field access is synchronized. JaCoCo uses a boolean array to keep track of the covered probes (that will be later translated to lines of code and branches). All that need to be done is set a array entry to true. There is no loss of information when multiple threads update the same entry concurrently.

Anyway, i agree with you. Probably removing the JaCoCo field will not introduce a  noticeable overhead (i guess). And I remember I read some JaCoCo GitHub issue proposing to remove this field (something related to attach JaCoCo to a running JVM).

**Comment by rliesenfeld** [comment]
Indeed, you're right. I checked JaCoCo's implementation, and it merely sets entries in a boolean array, without synchronization. This is only possible because such coverage data is minimal; not possible for JMockit Coverage, which measures the number of times each line of code gets executed, and (optionally) captures the stack trace so it can report the line in test code which led to the execution of the line in production code.

**Comment by marchof** [comment]
FYI: I just applied @rliesenfeld's proposal above to JaCoCo master in https://github.com/jacoco/jacoco/commit/bc47c020906fde9ce162597cf499fb66e73920fb.

**Comment by momandkp** [comment]
The <exclude>*$Impl_*</exclude> work around is not working for me.  Any other advice?

**Comment by marcdonovan** [comment]
switch to JMockit Coverage

**Comment by momandkp** [comment]
I can't do that.  Company mandate is to use Jacoco.  :(

**Comment by marcdonovan** [comment]
Present your case.

You can invite me and Rogerio to the conversation.

**Comment by rliesenfeld** [comment]
@momandkp I suspect your problem is different from what was originally reported in this issue, since jacoco now avoids changing the schema of classes generated at runtime. Are you getting the "class redefinition failed: attempted to change the schema (add/remove fields)" error message?

In any case, if a reproducible test case & project configuration can be shown, I would have a look.

**Comment by ignaciotcrespo** [comment]
same problem here running tests manually with gradle and jacoco coverage enabled. Added a filter in jacoco

**/*$Impl_*,
**/*$Subclass_*,
but still fails.

Running the tests from Android Studio works ok.

UPDATE: based on #415 I changed jmockit version to 1.8 and works perfect
