### ISSUE TITLE
2-3x slowdown when using Java8 compared to Java7

### ISSUE THREAD

**Issue by jevring** [jmockit/jmockit1#143]
I have a set of unit tests (jUnit 4.12) that use jmockit (1.15), and I build via maven (3.2.5). When I build these with java 7 it takes just under 3 minutes. When I build with java 8 it takes around 8 minutes. Looking at jvisualvm samples (I'm not allowed to use the profiler, for some reason, with jmockit), it would seem that the problem is with the redefinition of the classes, which dives into the ASM code.

**Comment by rliesenfeld** [comment]
As answered in the JMockit Users mailing list (https://groups.google.com/forum/#!forum/jmockit-users):

Here is what I see, when running JMockit's own test suite (JUnit 4.12), with nearly 1400 tests:

JDK 1.8.0_31: 22s
JDK 1.7.0_75: 21s
JDK 1.6.0_45: 19s

Times above as reported by IntelliJ IDEA 14.0.2, on Windows 7. Multiple executions with each JDK were performed, all else being equal.

As you can see, there isn't much difference (about 1s = 4.8%) going from JDK 1.7 to 1.8, and it is even smaller than the difference from JDK 1.6 to 1.7 (about 2s = 10.5%).

**Comment by jevring** [comment]
For unknown reasons I can't see questions posted to that group (by myself) and I couldn't read that link. Regardless, I don't know if you make heavy use of jmockit in your own tests, but we're seeing significantly worse numbers than that. After converting some sample tests to use other mocking frameworks we see significant speedups when using java8, so it's not the tests themselves.

Is it possible that there are some jmockit patterns that have gotten slower in java8 that should generally be avoided? It's perfectly possible that we've been misusing jmockit, but I'd like to think that it can't JUST be that, as the performance was reasonable on java 7.

**Comment by rliesenfeld** [comment]
The JMockit project has several sample test suites (both JUnit and TestNG), totaling about 500 tests (in addition to the 1400 tests from the main test suite). I run them from IntelliJ, Ant, and Maven, but never experienced a significant slowdown with Java 8.

There are no coding patterns I know about that would make execution with Java 8 significantly slower, but I would be happy to examine any reproducible evidence that shows otherwise.

**Comment by jevring** [comment]
It's highly reproducible. I just can't give you our code... Let me see if I can come up with a representative example that takes significantly longer in Java 8...

**Comment by rliesenfeld** [comment]
For completeness, when I run JMockit's test suite from Maven (the "test" goal), I get the following total build times as reported by Maven:

JDK 1.8: ~30s
JDK 1.7: ~29s

**Comment by rliesenfeld** [comment]
Don't know how to reproduce; please reopen if more information becomes available.

**Comment by bliessens** [comment]
@jevring,  while back we experienced a similar performance degradation when upgrading to jmockit 1.14. The 1.14  release made the Injectable and Mocked annotations cascading by default.

I have forked the latest jmockit and made the cascading behaviour optional again. E.g. use @Mocked(cascading = true)) or @Injectable(cascading = true) to restore the normal behaviour. This does make our build faster again - though not by a factor 2.
Note: because of the changed behaviour you might need to add the 'cascading=true' attribute to some of your tests.
The branch is named 'optional_cascading': https://github.com/bliessens/jmockit1/commits/optional_cascading
