### ISSUE TITLE
Partial mock on dynamically proxied Spring class does not work

### ISSUE THREAD

**Issue by robert-bor** [jmockit/jmockit1#202]
When you have an injected Spring service that has a Dynamic Proxy created for it, and you create a partial mock with an invoke expectation on a private method, the actual method is called, not the mocked method.

The testcase is available in its stripped down form: https://github.com/42BV/jmockit-partial-on-dynamic-proxy-testcase

See SomeServiceTest.publicCallOnDynamicProxy()

Note that caching is enabled in the project to force Spring to create a DynamicProxy on the service. Without the Dynamic Proxy the case works as expected; see SomeServiceTest.publicCallOnConstructedService().

**Comment by rliesenfeld** [comment]
Partial mocking on a mocked instance only applies to methods called on that instance. So, when the test calls `invoke(someService, "privateCall")`, it's invoking the method on the `someService` proxy instance. The call to `someService.publicCall()` occurs on the same proxy instance, but it gets redirected by the proxy to a call on `publicCall()` on a *different* instance (the actual service object), which then calls `privateCall()` on this same instance, which is not the proxy instance used when recording the expectation.

So, this is the expected behavior from the mocking API. Should this behavior be extended to deal with proxied objects? I don't know, probably not, but it would need more thought.

In any case, partial mocking is generally considered a bad practice, and using it to mock `private` methods is even worse. So, the best "solution" here, IMO, is to rethink the testing approach.

**Comment by robert-bor** [comment]
Thank you for your answer. Indeed, this is the first time we encounter this particular problem and I heartily agree with you that this testing approach is not the right way to proceed.

Nevertheless, we are likely to see more and more proxies in the future. It would be nice if JMockit (which is our favorite mocking tool) would be able to handle proxies. 

Also, if a partial mock has been implemented in a pre-caching / pre-transactional stage and have been seen to work, these tests will suddenly break with the enabling of caching or transactions.

For http://beanmapper.io we ran into similar issues with proxies and decided to implement an unproxy approach. See package:

https://github.com/42BV/beanmapper/tree/master/src/main/java/io/beanmapper/core/unproxy

Feel free to adopt any code you require.

**Comment by rliesenfeld** [comment]
The BeanUnproxy#unproxy(beanClass) method takes a Class and returns a Class, but what's needed is a method that takes a proxy Object and returns the internal proxied Object. It's unclear how this could be achieved.

I am also unclear on legitimate use cases.
