### ISSUE TITLE
Lines of code reported as not covered that have to have been exercised when class loaded

### ISSUE THREAD

**Issue by jimshowalter** [jmockit/jmockit1#217]
I have several files that jmockit says have low coverage, but the lines marked in red make no sense, because the classes couldn't have loaded without calling the code. For example, some of the code marked in red is for enum constructors. The constructors are called when defining the enum values. The class is loaded (as shown by green in other parts of the class), so the red can't be correct.
![statics](https://cloud.githubusercontent.com/assets/211780/10441759/518d906e-7101-11e5-8754-a4553a09b6b9.png)
![enums](https://cloud.githubusercontent.com/assets/211780/10441760/51909728-7101-11e5-940a-7e1f1b236683.png)

**Comment by rliesenfeld** [comment]
The lines not covered in the report (in red), most likely, were executed *before* the coverage tool got the chance to instrument them. This happens normally, if the code was not exercised through a JUnit/TestNG test suite, and the coverage tool was not initialized by using the "-javaagent" JVM parameter.

The likely solution here is to use "-javaagent:jmockit-coverage.jar" to run the code, so that the coverage tool can install its bytecode transformer at JVM startup, before any application classes get loaded.

**Comment by jimshowalter** [comment]
Well duh.

Fixed.

![coverage](https://cloud.githubusercontent.com/assets/211780/10463647/94ea586c-719a-11e5-99fe-88a081548de1.png)
