### ISSUE TITLE
Provide API to create mocks on the fly

### ISSUE THREAD

**Issue by piefel** [jmockit/jmockit1#232]
Declarative mocks in JMockit are usually easy to use, but sometimes it may be easier to create a mock on the fly, programmatically, the way Mockito does it. I don’t want to go into discussions whether there always is a better way, JMockit style, but present instead a case where that is necessary.

For unit testing with Spring contexts, using different [Spring test utils](http://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/integration-testing.html), you usually build a test context that contains a number of real beans but mocks out most of them. Some would call that integration tests. One such example are `AbstractTestNGSpringContextTests` using `@WebAppConfiguration` and `MockMvc`. The whole point here is to have a Spring context to perform MVC calls against (using `mockMvc.perform(get("/api/…"))…`).

Now, the problem is that this Spring context is built before JMockit creates the mocks for `@Mocked` or `@Injectable`. That means Spring sees the real classes, requiring the dependencies of those (and so on) and also running the `@PostConstruct` methods etc. A programmatic way to create mocks would allow to populate the context with mock beans.

**Comment by rliesenfeld** [comment]
Are you sure this kind of testing works well with Mockito? Did you actually tried it with some realistic code under test?

I looked around, and found the following set of articles which shows example tests using Spring Test and Mockito:

http://www.petrikainulainen.net/programming/spring-framework/unit-testing-of-spring-mvc-controllers-configuration

https://github.com/pkainulainen/spring-mvc-test-examples/blob/master/controllers-unittest/src/test/java/net/petrikainulainen/spring/testmvc/todo/controller/WebApplicationContextTodoControllerTest.java

Personally, it seems a bit too cluttered with Spring annotations, configuration classes, and those `mockMvc.perform(...).andExpect...` calls full of strings and constants.

There are certain difficulties with the Spring + Mockito combination:
1. Mocks created by Mockito.mock but called from Spring need to be reset (by calling `Mockito.reset(mock)`) in a test setup method, to avoid previous invocations to the mock from affecting the next test, since Spring creates beans only once for the entire test class. JMockit would have to do the same, although it could probably be done automatically.
2. If a SUT class has a `@PostConstruct` method, it will probably require stubbings/expectations to have been previously recorded when the mock object was created. This means that Spring's "Java config" would have to be used, since XML config would not (I imagine) allow calls similar to "when(...).thenReturn(...)". It also means that JMockit's expectation blocks would have to be allowed in arbitrary classes, rather than just in test classes.

JMockit already provides the Mockups ("faking") API, with which you can write
`new MockUp<SomeDependency>() { ... }.getMockInstance()` in a Spring @Configuration class. It allows mock instances to be created with fake results/behavior, from inside those configuration methods that return Spring beans.

If not for `MockMvc`, JMockit's support for integration tests through `@Tested(fullyInitialized = true)` would be an alternative. For a Java EE web app, it works really well, with much cleaner tests than the equivalent Spring MVC ones. (Probably in part because JSF 2+PrimeFaces is far superior to Spring MVC.)

As for using the Expectations API inside @Configuration classes, I will need to give it more thought.

**Comment by piefel** [comment]
I am not quite sure whether I understand your question. Are you somehow suggesting that I haven’t yet used Spring MVC testing and Mockito? Well, I did. We have many tests with that combination, and with the Spring transactional tests as well (for testing Spring Data).

Your analysis is quite right. Without `Mockito.reset(…)` most of the test suites won’t work too well; however, one could also use `@DirtiesContext` at the expense of slower tests (which have to recreate the Spring context more often). And a SUT with `@PostConstruct` might require stubbing/expectations while setting up the context; that _may_ well be a rare case, as those tests are mainly against `@Controller`s (and ours, at least, have no `@PostConstruct`) and Spring Data `Repository` interface (which cannot have `@PostConstruct`.

I have not much experience with the `MockUp` API, but if I have read it correctly, it creates partial mocks that by default call real methods, not mocks that by default mock all methods. That’s quite a difference, also the API is more verbose.

**Comment by rliesenfeld** [comment]
It was my impression, after some google searching, that people don't often use Spring Test + Mockito. I am sure you have, though. That said, it does seem somewhat questionable, since Spring Test, in particular when using MockMvc, is meant for integration tests where dependencies are *not* mocked. Personally, I much prefer integration tests with no mocking, whenever possible (in my case, I did/do so for Java EE 7 and Spring 2.5+Struts web apps).

Yes, Mockups are always partial mocks.

You say you don't have `@PostConstruct` methods in you Spring beans. That being the case, use of `@Capturing` in a Spring-based test should work fine with whatever Spring configuration is used, provided bean constructors don't perform any work beyond setting fields from constructor parameters. Did you try converting a test using Spring+Mockito to make use of `@Capturing` and the Expectations/Verifications API?

**Comment by piefel** [comment]
People do use Spring Tests + Mockito, as a project such as [Springockito](https://bitbucket.org/kubek2k/springockito/wiki/Home) shows. These tests are, in fact, not pure unit tests, but integration tests. Still, it is sometimes necessary to use a modified Spring context to exclude usage of external resources (be it databases or REST services) and inhibit running initialization code of some grizzly old artefacts that are out of our hands.

Anyway, I found (or: you showed me) enough ways now to test all that I need, so I am quite content. Thanks for your time!
