### ISSUE TITLE
Removal of NonStrictExpectations class

### ISSUE THREAD

**Issue by rolger** [jmockit/jmockit1#304]
Hi Rogério 

I want the understand reason behind removing the NonStrictExpectations feature from your JMockit library. Especially because 
* we have a lot of tests to migrate (> 1.000) and even don't know if the MockUp<> feature will be sufficient for all cases
* which legacy code testing feature is going to be removed next (so this is a question about your long-term JMockit strategy)

We really appreciate your library. We have a huge development team and we are maintaining a code base of  more than 1 million LOC. This code was originally migrated to Java from a procedural programming language, so most of the established object-oriented design principles and practices still don't apply to our code. Further there have been design and architectural decision which can't be changed anymore for example the former team developed a framework based on inheritance (usally I'd prefer composition instead). We have chosen to use JMockit because otherwise we won't be able to write Unit Tests for a lot of our code. Currently we have developed more than 10.000 Unit Test depending on different JMockit's features.

So our primary question is, why have you removed the NonStrictExpectations feature and what is your long-term strategy in supporting mocking and unit testing in legacy code environments?

Thanks for your answer in advance,
roland

**Comment by rliesenfeld** [comment]
It's simple, NonStrictExpectations was removed because it didn't add enough value to justify its existence, when compared to the Expectations class.
More specifically:

1. "Expectations" is a shorter, easier to type name.
2. Expectations provides all the functionality that NonStrictExpectations did. The difference is only that the *default* value for the "minTimes" field on a recorded expectation (its minimum invocation count constraint) is 1 (one) with Expectations, while it was 0 (zero) with NonStrictExpectations. Tests that need it can simply add "minTimes = 0;".

The only other feature that I am considering (but haven't decided yet) to remove in the future is the "invocations", "minInvocations" and "maxInvocations" attributes of the @Mock annotation. Do you use any of them?

**Comment by rolger** [comment]
Thanks, for your reply. The solution you have been describing is completly sufficient for us.

I had a look at our tests and found just one usage of the "invocations" attributes of the @Mock annotation. In my opinion this is not necessary at all and can be replaced easily.

Thank you again for supporting this powerful framework.
