### ISSUE TITLE
@Injectable for @Resource not working properly

### ISSUE THREAD

**Issue by Spookyguy** [jmockit/jmockit1#396]
Please provide the following information:

* Version of JMockit that was used: 1.30

* Description of the problem:

I got an @Resource annotiation in my code like that one:

@Resource(name = "java:jboss/datasources/my-ds")

and try to inject in the testcode via @Injectable, which obviously does'nt work regarding to the behaviour described in issue #359

**Comment by rliesenfeld** [comment]
It works fine when the `@Resource(lookup = "...")` attribute is used instead of `@Resource(name = "...")`:
```
public class SomeClass {
    @Resource(lookup = "java:jboss/datasources/my-ds") private DataSource ds;
}

public SomeTest {
    @Tested SomeClass tested;
    @Injectable DataSource myDs;
}
```
From what I understand about the `@Resource` annotation's attributes, `name` is always relative to the component's local naming context, so eg. `name = "my-ds"` actually means a JNDI path of `java:comp/env/my-ds`. So, you should *not* use `name` for a global JNDI path like `"java:jboss/..."`. Such paths can only appear in the `lookup` attribute (or in `mappedName`, but this is non-portable and probably never needed/used). See [this](https://coderanch.com/t/622076/certification/Resource-lookup) for more.

(Also, it seems wrong to have the word `"jboss"` in a JDNI path, as it wouldn't make sense in a non-JBoss app server - but this is a nitpick.)

**Comment by pedorro** [comment]
I'll just briefly reiterate my comment from the linked issue #359. It seems to me that the best, and most obvious way to handle named injected dependencies is to use the actual name String as a parameter to the @Injectable annotation. So injected bean:
`@Resource (name = "some_terrible/bean:name") AClass aClass;`

could be injected into a test like so:
`@Injectable (name = "some_terrible/bean:name") AClass aClass;`

Is this a possible option?
