### ISSUE TITLE
Self attach fails on JDK9

### ISSUE THREAD

**Issue by sdfelts** [jmockit/jmockit1#418]
Starting with b169, self-attach is only supported with a system property.
The work-around is to start another process and attach back to the original process.
See the recent changes to ByteBuddy for a sample how this can be done.

**Comment by rliesenfeld** [comment]
Thanks for letting me know.

For now, use of "-Djdk.attach.allowAttachSelf" will be needed to run on JDK 9. I will wait to see what happens until the final release of JDK 9.

Personally, I think the JDK 9 developers should just add an "InstrumentationFactory" class (with a "newInstrumentation()" method) which is what the java.lang.instrument API should have had since the beginning; JMockit doesn't actually need a "Java agent", it only needs an Instrumentation object for the running JVM. In the end, use of this API from the same process is by far the major use case for it (for example, JaCoCo and Byteman are other tools which use it like that), not what the Sun engineers originally imagined it would be (ie, tools like JConsole).
