### ISSUE TITLE
Performance issue when moving from 1.0 to 1.32

### ISSUE THREAD

**Issue by wattazoum** [jmockit/jmockit1#426]
## Description of the problem:

We have upgraded our version of JMockit from 1.0 to 1.32 (mostly due to JAVA 8 migration). 
Since then, we have an increase of our execution time (x3). 

The context in which we use JMockit is for functional testing with a tool called Greenpepper ( same goal as Cucumber). A test run is made by forking a JVM (like surefire)
To do our automated tests, we Mock some classes that should be mocked during the whole run. we use the `Mockup<T>` way for that.

The java command is not launched with `-javaagent:` but the jar is in the class path.  
The coverage is not activated. 
Every thing is working fine but a have a performance issue in the test. 

### Observations in 1.0: 

If I understand well, in Jmockit 1.0, when using `@MockClass`, the bytecode of the targeted class where changed in the Classloaders when calling `Mockit.setupMocks(...)` . Then Jmockit were not used during the run.

### Observations in 1.32

I ran the test and recorded the run in Yourkit JP. When I look at the methods taking the most time (hotspots) the 5 firsts are JMockit's (for a run that took 3 minutes). In 1.0 the run takes 1 minute.

![image](https://user-images.githubusercontent.com/11292115/27510677-23941a62-5916-11e7-8b7e-44e672cd9ed1.png)

We also see that the `retransform` method is called more than 1000 times. But we want to mock only 6 classes. It's like jmockit changes the bytecode everytime we access the class. I would expect it to change the bytecode once and for all.

**Comment by rliesenfeld** [comment]
Yes, somehow JMockit is being made to perform bytecode processing repeatedly, when it should only have happened at the start of the test run. Naturally, this is going to impact the total execution time.

Without more information, though, there is nothing more I can say.

**Comment by wattazoum** [comment]
Hi, 
Thank you for your quick reply. If I understand correctly, this is an unexpected behavior due to my context, right ? 

I am trying to pinpoint the exact context creating that. I am also trying to make a test project for that purpose.

**Comment by wattazoum** [comment]
When I debug the test I see that it's not only the Mockup classes that are being retransformed, but every classes (it seems). I would expect that behaviour for coverage. Is there any way to activate coverage beside system properties ?

**Comment by rliesenfeld** [comment]
"Is there any way to activate coverage beside system properties ?"

No, not anymore.

**Comment by wattazoum** [comment]
Hello there, 

I have pinpointed the right scenario to reproduce. If one follows the Faking procedure in http://jmockit.org/tutorial/Faking.html#implementationClasses , he will get every classes being retransformed. 

Test project: https://github.com/zoomonit/jmockit-perftest

You get the problem if you write :+1: 
```
public class MockDefaultHttpClient<T extends InternalHttpClient> extends MockUp<T> {
```
but no problem if
```
public class MockDefaultHttpClient extends MockUp<InternalHttpClient> {
```

**Comment by rliesenfeld** [comment]
So, there is no actual problem, right? When the first form is used (`MockUp<T extends ABaseType>`), the fact the bytecode of every class gets read is as expected, since JMockit needs to determine whether it implements/extends the base type or not.

In your case, that feature is not needed, right? So just using "MockUp<T>" avoids the issue.

**Comment by wattazoum** [comment]
Well, my problem was actually with Faking the [SocketClient](https://commons.apache.org/proper/commons-net/javadocs/api-3.6/org/apache/commons/net/SocketClient.html) class from commons-net. That class is abstract so I can't use the MockUp<T> form. Still I have fixed my problem by finding the most common implementation of that class that was used in our application (FTP.class) .  

Now about the performance problem, I am not sure it's normal that the `mockit.internal.startup.InstrumentationHolder#retransformClasses` is called for every classes. According to the documentation, that method is called for transforming already loaded classes. But if the classes are already loaded, we can get enough information on them to know that they don't need transforming, right ?

**Comment by rliesenfeld** [comment]
`SocketClient` *can* be faked with a `MockUp<SocketClient>`, for example:
````
      new MockUp<SocketClient>() {
         @Mock
         void connect(String hostname, int port) { System.out.println(hostname + port);}
      };

      new FTP().connect("test", 123);
```
(In fact, the class has no `abstract` methods at all.)
But, of course, it's best to target the actual subclasses of interest, such as `FTP`, as you did.

As for `InstrumentationHolder#retransformClasses(Class...)`, this method is only called when JMockit is asked to mock (with `@Mocked`, etc.) or fake (with `MockUp`) a type, *or* by the `CaptureTransformer` when it needs to check whether a given newly loaded type is a subtype of a captured base type (the "T" in `MockDefaultHttpClient`). No actual "retransformation" occurs (it's just a way to obtain current bytecode of the type without reading it from a .class file). This can indeed occur a large number of times, if the "capturing" mockup stays in effect for many tests.

In this case, the performance problem arose because of a) `MockUp<T>` was inadvertently/erroneously used in its "base type capturing" form, and b) the capturing mock-up was applied in a `main` method, staying in effect for an entire test run, leading to constant attempts to "capture" a potential subclass of the target base type. Both things are unusual. Fortunately, the solution here is simply to avoid the capturing form of MockUp when it's not needed.

This said, I am open to improving the performance of the `CaptureTransformer` in the future - for now it doesn't seem to be causing problems in the more "usual" use cases.

**Comment by wattazoum** [comment]
Thank you very much for the clarifications. That is something I will keep in mind in the future.
