### ISSUE TITLE
Mocking of thrown exception with mocked dependency fails

### ISSUE THREAD

**Issue by Milbor** [jmockit/jmockit1#443]
1.33 fails
1.29 green
New undocumented feature?

```
import org.springframework.ws.soap.SoapMessage;
import org.springframework.ws.soap.client.SoapFaultClientException;
import org.testng.annotations.Test;

import com.google.common.base.Supplier;

import mockit.Expectations;
import mockit.Injectable;

public class JmockitTest {
    @Injectable
    private Supplier<Object> supplier;
    @Injectable
    private SoapMessage soapMessage;

    @Test(expectedExceptions = SoapFaultClientException.class)
    public void test() throws Exception {
        new Expectations() {{
            supplier.get();
            result = new SoapFaultClientException(soapMessage);
        }};
        supplier.get();
    }
}
```

**Comment by rliesenfeld** [comment]
Nothing wrong, except the test. Note the exception message says:

> Caused by: Missing 1 invocation to:
> org.springframework.ws.FaultAwareWebServiceMessage#getFaultReason()

Which is correct, since a call to the mocked method `soapMessage.getFaultReason()` was (inadvertently) recorded from inside the expectation block.

To fix, simply move the creation of the exception outside the block. In general, avoid unnecessary method/constructor calls inside expectation/verification blocks, particularly when passing other mocked instances in said calls. Even better, reduce mocking to a minimum (none ideally).
