### ISSUE TITLE
Why does jmockit re-package org.junit.runner.Runner?

### ISSUE THREAD

**Issue by MLBenjii** [jmockit/jmockit1#447]
Please provide the following information:

* Version of JMockit that was used: 
1.33

* Description of the problem:
I am trying to use a facility in ElasticSearch 5.5.0 for integration testing (ESIntegTestCase abstract class) which attempts to verify its execution environment by looking for JarHell (duplicate definitions of classes). This fails due to the presence of org.junit.runner.Runner in JUnit and JMockIt. Why is this class packaged in jmockit?

Appreciate any insights! Thanks.

**Comment by rliesenfeld** [comment]
It's because JUnit 4 does not provide any better alternative for transparent integration of a tool like JMockit into its test runner, unlike TestNG and JUnit 5 which do provide clean solutions. Without that class duplicated in jmockit's jar, users would be forced to either use "@RunWith(JMockit.class)" in every test class, or always run with "-javaagent:jmockit.jar"; both of these alternatives are not desirable for several reasons.
