### ISSUE TITLE
Best practice in replacing NonStrictExpectations

### ISSUE THREAD

**Issue by WatchfulLikeACrane** [jmockit/jmockit1#462]
I got a follow up question after reading #335. I wholeheartedly agree with the premise that test should focus on validating a clearly defined contract and removal of NonStrictExpectations but I'm having second thoughts  in the following scenario:

```
    class Dependency {   // non-value class
        boolean getA() { ... }
        boolean getB() { ... }
    }

    class TestedClass {
        public boolean isAandBtrue(Dependency d) {
            return d.getA() && d.getB();
        }
    }
```

I believe that, without knowing anything about the implementation, it's fair to EXPECT both getA() and getB() called by isAandBtrue() here. In the past, I'd get away with writing following:
```
   @Injectable
    Dependency dependency;
    @Tested
    TestedClass tested;

    @Test
    public void test() {

        new NonStrictExpectations() {{
            dependency.getB(); result = true;
        }};

        new Expectations() {{
            // dependency.getB(); result = true;
            dependency.getA(); result = false;
        }};

        tested.isAandBtrue(dependency);
        assert ...
    }
```
From my perspective, it's a very concise and clear way of writing such test without having to use MockUps. Even more so, when the tested method works on the `List<Dependency>` and different MockUp is needed for each Dependency object. 

I realize that this is might be a corner case and all in all removing the NonStrictExpectations is a good change but I'd be quite interested to hear your approach to tackle such test case as the owner of JMockit.

**Comment by rliesenfeld** [comment]
I would write such a test in one of two ways, depending on whether there is a good reason to mock `Dependency` or not. (In general, I advise against mocking classes from inside the codebase under test, since good tests focus on exercising meaningful "business" behavior scenarios, not on somewhat arbitrary units of code.)
```
   @Tested TestedClass tested;

   @Test
   public void usingMockedDependency(@Injectable Dependency dependency) {
      new Expectations() {{
         dependency.getB(); result = true;  minTimes = 0;
         dependency.getA(); result = false; minTimes = 0;
      }};

      boolean result = tested.isAAndBTrue(dependency);

      assertFalse(result);
   }

   @Test
   public void usingRealDependency() {
      Dependency dependency = new Dependency(false, true);

      boolean result = tested.isAAndBTrue(dependency);

      assertFalse(result);
   }
```
Note the first test uses `minTimes = 0` to obtain an "optional" expectation which may or may not get called from the tested code. This is equivalent to the old `NonStrictExpectations`. The "need" for such expectations in a test, IMO, indicate they are being used to simulate *state* (typically, calls to "getters") rather than "behavior" (calls to methods that do more that merely returning a piece of instance state).

Mocking is not meant for simulating instances in a particular state (whether they are "value objects" or not), but for simulating the non-trivial behavior of some dependency. If the dependency object can be created in a suitable state without mocking, then that's a better choice, as the second test shows.

**Comment by WatchfulLikeACrane** [comment]
Clear. All good points. Thanks!
