### ISSUE TITLE
API changes report for JMockit 1.x

### ISSUE THREAD

**Issue by lvc** [jmockit/jmockit1#476]
Hi,

I'd like to share report on API changes and backward compatibility for the JMockit library: https://abi-laboratory.pro/java/tracker/timeline/jmockit/

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jmockit-1](https://user-images.githubusercontent.com/1517837/32208770-af7ffa8c-be15-11e7-8bc3-c5e467e62b8b.png)

![jmockit-2](https://user-images.githubusercontent.com/1517837/32208769-af5d62ce-be15-11e7-86b2-c3aa49c43a3a.png)

**Comment by karypid** [comment]
This is a nice tool, I was not aware of it. Looking at it this way makes me thing that 1.36 probably should've been called 2.0 instead. Thanks for sharing!

**Comment by rliesenfeld** [comment]
Actually, this report is not helpful at all, since it fails to identify what is part of the API and what is not (ie, *published* API elements from *internal* implementation code).

For example, that big jump up in the graph (from version 1.23 to 1.24) was due to the `mockit.coverage` classes, previously distributed in a separate jar, being incorporated into JMockit's "main" module and jar file. And the entire `mockit.coverage` package is not part of the API.

And while there were some API removals in version 1.36, most of those 46 added + 31 removed methods were due to refactorings inside the `mockit.external.asm` package, which again are not part of JMockit's API.

So, those "backward compatibility" percentages are essentially meaningless. BTW, I couldn't quite make sense of what "BC" (Binary Compatibility) and "SC" (Source Compatiblity) are even supposed to mean. There is no description that I could find.

For it to be helpful the report would have to only measure changes to actual API types (ie, only those directly in the "mockit" package), ignoring all the internal non-API code.

**Comment by rliesenfeld** [comment]
Ah... reading that Eclipse article and [one at Wikipedia](https://en.wikipedia.org/wiki/Source-code_compatibility), it's now obvious that the "japi-tracker" tool's "SC" is only applicable to interpreted languages such as Python, not to Java where the library is delivered as binary code (.class files, where .java files are only for documentation purposes).

**Comment by lvc** [comment]
@rliesenfeld,

> For it to be helpful the report would have to only measure changes to actual API types (ie, only those directly in the "mockit" package), ignoring all the internal non-API code.

Fixed: https://abi-laboratory.pro/java/tracker/timeline/jmockit/

Thank you.

![jmockit-3](https://user-images.githubusercontent.com/1517837/32412510-d9bf1596-c20a-11e7-9113-71a20cb72c12.png)

![jmockit-4](https://user-images.githubusercontent.com/1517837/32412509-d99d81ba-c20a-11e7-8331-5dc19661de37.png)

**Comment by lvc** [comment]
@rliesenfeld,

> "japi-tracker" tool's "SC" is only applicable to interpreted languages such as PHP, or to languages which require building the binaries from source for full portability (such as C/C++), not to Java where the library is delivered as a single binary artifact for multiple platforms (.class files, where .java files are only there for documentation/debugging purposes)

In the context of this analysis, SC (backward *source-compatibility*) means ability to recompile a client code with a new version of the library `*.class` files. And it's differ from BC (backward *binary-compatibility*) — ability to run (without recompile) a client code with a new version of the library `*.class` files.

Please see http://motlin.com/2010/binary-and-source-backwards-compatibility/.

Thank you.

**Comment by rliesenfeld** [comment]
Thanks for the update, it's a lot better now. And you're right about the meaning of "SC", it's about the ability to recompile client code without any changes.

The tool still has some issues, though. One is that is treats Java annotations as if they were interfaces. For example, it shows that version 1.32 added a "method", when in reality it's an annotation attribute. That's actually ok, but it regards it as a new method in an interface, which would break Source Compatibility if it really was the case. But since it's an annotation attribute, there is no actual SC reduction. Another little problem here is that the tool counts the added method also as "Other Changes
in Data Types", resulting in the SC percentage of 96.2% when it should've been about 98%.

Also, the tool does not account for *fields* that may be part of a Java API. This is unusual, of course, but in the case of JMockit fields make up a significant part of the API. Version 1.27 removed the "$" field from the Expectations class, a SC break the tool did not detect.

**Comment by lvc** [comment]
There is a lot of good points in your review. Excellent.

I need some time to fix all of them.

Thanks a lot!
