### ISSUE TITLE
getMockInstance returns null

### ISSUE THREAD

**Issue by novaterata** [jmockit/jmockit1#477]
Please provide the following information:

* Version of JMockit that was used: 

1.36 (did not happen in 1.35)

* Description of the problem:

Starting with 1.36 I started getting null mock instances for various MockUp instances I was using. I found workarounds, but it is definitely a regression.

       String fileName = "foo";

        new MockUp<File>() {
            @Mock
            public boolean exists() {
                return !getMockInstance().getName().equals(fileName); // NPE because getMockInstance() is null
            }
        };

**Comment by rliesenfeld** [comment]
It worked before merely by accident (probably a bug), since "getMockInstance()" is supposed (per API documentation) to return an *uninitialized* instance of the faked class. In this case, that's what it does, returning a `File` instance where the internal "path" field is null, which causes the NPE when File#getName() is called.

If the test intended to obtain the `File` instance on which the `exists()` call was made, it should have used `Invocation#getInvokedInstance()`, not `MockUp#getMockInstance()`. Then, it works as expected.
