### ISSUE TITLE
What if more than one injectable/tested of same field name and same type are found ? 

### ISSUE THREAD

**Issue by hzdavid** [jmockit/jmockit1#490]
At the tutorial: http://jmockit.org/tutorial/Mocking.htm
It says:
Once the tested class is initialized with the chosen constructor, its remaining uninitialized non-final instance fields are considered for injection. For each such field to be injected, an injectable/tested field of the same type is searched in the test class. If only one is found, its current value is read and then stored in the injected field. If there is more than one, the injected field name is used to select between the injectable/tested fields of same type.

What if more than one injectable/tested of same field name and same type are found ? 

Choose anyone of them ?

**Comment by rliesenfeld** [comment]
If there is "more than one injectable/tested of same field name and same type" to be found, then:
a) your test class is poorly written, as it *shouldn't* declare multiple injectable/tested values of same type and name;
b) JMockit uses the *first* injectable/tested value that gets found among the test class fields and test method parameters which are in scope. Because of a), this of course should never happen.

**Comment by hzdavid** [comment]
Thank  you.
