### ISSUE TITLE
Mocked System.currentTimeMillis() occasionally returns current time instead of mocked value

### ISSUE THREAD

**Issue by jason-tishler** [jmockit/jmockit1#493]
Please provide the following information:

* Version of JMockit that was used: 

1.37

* Description of the problem:

We are using a MockUp to mock System.currentTimeMillis(). Occasionally, some of our unit tests fail because the mocked System.currentTimeMillis() erroneously returns the current time instead of the mocked value.

I have extracted the essence of our problem into a test harness that consistently demonstrates the same or similar problem:
```
import static org.junit.Assert.*;

import org.junit.Test;

import mockit.Mock;
import mockit.MockUp;

public class MockSystemTest
{
    private static long NOW = 1420070401000L;

    @Test
    public void test() throws Exception
    {
        new MockSystem();

        for (int i = 0; i < 100000; i++)
        {
            String message = "i = " + i;
            assertEquals(message, NOW, System.currentTimeMillis());
        }
    }

    private static final class MockSystem extends MockUp<System>
    {
        @Mock
        public static long currentTimeMillis()
        {
            return NOW;
        }
    }
}
```

The above will fail after approximately 61440 iterations as follows:
```
java.lang.AssertionError: i = 61442 expected:<1420070401000> but was:<1513198371555>
	at com.tds.efx.ed.te.MockSystemTest.test(MockSystemTest.java:22)
```

**Comment by rliesenfeld** [comment]
Yes, this issue was noticed long ago (can't find the issue now, probably was in the old Google Code site).

There is nothing JMockit can do about it, since it's a defect in the JVM. The HotSpot JIT optimizer knows nothing about the class redefinitions done through `java.lang.instrument`, so it eventually "inlines" calls to `System.currentTimeMillis()` by directly calling the native JVM code that reads the system clock. This bypasses the temporary fake implementation put in place by a `MockUp<System>`. The JVM optimizer should, of course, *not* perform such an optimization when the `System.currentTimeMillis()` method is redefined; but, unfortunately, it apparently doesn't check for that.

**Comment by jason-tishler** [comment]
Right before you responded, I realized this might be happening after tweaking my test case. Thanks for the confirmation.

I am able to workaround this issue by disabling HotSpot JIT compiler inlining (e.g., -XX:-Inline).

**Comment by greghmerrill** [comment]
-XX:-Inline didn't get the job done for me (I am using Oracle JDK 1.8).  The JVM still inlined the original, non-instrumented currentTimeMillis after a few minutes had passed.

I had better luck with -XX:CompileCommand=exclude,*.*

In our case we're just using this for simulations/testing (not production), so we're OK with the performance implications of disabling all this JIT compliation & inlining.
