### ISSUE TITLE
No result recorded with JUnit5 and Gradle 4.6

### ISSUE THREAD

**Issue by MichalMichalak** [jmockit/jmockit1#508]
Please provide the following information:

* Version of JMockit that was used: 1.38 (with JUnit5 Jupiter 5.1.0 and Gradle 4.6)

* Description of the problem: Mock is defined, mocked method called, but recorded result is not returned. Instead result is null. Gradle introduced quite few changes to the API in version 4.6, may it be the reason?

* Build script
```
plugins {
    id 'java'
}

tasks.withType(JavaCompile) {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

def junitEngineVersion = '5.1.0'

dependencies {
    testCompile 'org.jmockit:jmockit:1.38'
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitEngineVersion"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitEngineVersion"
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}
```

* Implementation classes:
```
public class Foo {
    private final Bar bar;

    public Foo(Bar bar) {
        this.bar = bar;
    }

    public String activate() {
        return "Active: [" + bar.bar() + "]";
    }
}
```

```
public class Bar {
    public String bar() {
        return "bar";
    }
}
```

* Test class:
```
class FooTest {
    @Mocked
    private Bar bar;

    private Foo getFoo() {
        return new Foo(bar);
    }

    @Test
    void fooBar() {
        new Expectations() {
            {
                bar.bar();
                result = "baz";
                times = 1;
            }
        };
        Foo foo = getFoo();
        String activate = foo.activate();
        Assertions.assertEquals(activate, "Active: [baz]"); // Actually returns "Active: [null]"
    }
}
```

**Comment by rliesenfeld** [comment]
Yep, reproduced it. It's due to some class loading shenanigan that Gradle 4.6 is doing.

Specifically, when the test is executed Gradle causes the anonymous `Expectations` subclass (here it's name is "FooTest$1") to get loaded by the JVM *before* it normally would. This prevents JMockit from instrumenting the expectation block, therefore causing the expectation to not actually get recorded; so, `Bar.bar()` will always return null.

This is what happens; let's see how to deal with it now...

**Comment by rliesenfeld** [comment]
Ok, so the problem is caused by a bug in Gradle's support for JUnit 5, in method "execute(String testClassName)" of https://github.com/gradle/gradle/blob/master/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java

It is unconditionally loading any class that could potentially be a nested test class. An inner class (which includes all anonymous classes) is excluded from being a test class. The way this check is implemented has the bug, where classes get loaded unnecessarily (generally, doing so will mess up any Java agent which installs a `ClassFileTransformer` some time after JVM startup). Gradle could fix it by checking the class name does not end with a "$" and an integer number (which means it is an anonymous inner class), before loading the class.

A work-around is to initialize JMockit at JVM startup time, before Gradle starts loading classes. This can be done in build.gradle with the following code:

```
test {
    useJUnitPlatform()
    def m2repository = new File(repositories.mavenLocal().url).absolutePath
    jvmArgs "-javaagent:$m2repository/org/jmockit/jmockit/1.38/jmockit-1.38.jar"
}
```

(Maybe there is a better way to obtain the m2 repository location, I couldn't find it.)

**Comment by MichalMichalak** [comment]
I found this to be a good way. It points to a file in `~/.gradle/` directory.
```
configurations.testCompile.files.find { it.name.contains("jmockit") }.name
```
