### ISSUE TITLE
StackOverFlow when mocking Thread.getName().

### ISSUE THREAD

**Issue by evdzhan** [jmockit/jmockit1#52]
Hi again, 

I want to report an issue I discovered recently.
When one mocks the Thread.getName method, a StackOverFlow occurs. I did debug the code, and it turns out that JMockit internal classes use the Thread.getName method. So when I mock it, an infinite recursion occurs.

Thanks.
JMockit Version 1.10.
JDK 1.7.0_51
OS Win7 64bit

```
    public class FooTest {
  @Test
     public void blahblah() {

    MockUp<Thread> Mockthread = new MockUp<Thread>() {
        @Mock
        public String getName() {
            return "Fake Thread";
        }
    };
    Thread thread = Mockthread.getMockInstance();


    System.out.println(thread.getName());
}
```

**Comment by dlipofsky** [comment]
While it looks like the example above was fixed in 1.12 I still get a stackoverflow for this test in 1.13

    @Test
    public void test2(@Mocked({ "getName" }) final Thread thread) throws Exception {
        new NonStrictExpectations() {
            {
                thread.getName();
                returns("Thread-1", "Thread-1", "Thread-2");
            }
        };
        System.out.println(thread.getName());
    }

and in 1.14 and beyond I get "java.lang.IllegalArgumentException: Attempted to record expectation on unmockable method".

Is there a better way to do this? My actual code isn't going to have a direct reference to the thread instance created in the test, it will be calling Thread.currentThread().getName()
