### ISSUE TITLE
Missing @Injectable if @Resource has name which contains / (slash)

### ISSUE THREAD

**Issue by Saljack** [jmockit/jmockit1#532]
jmockit version 1.40

I have project where are used `@Resource(name = "xxx/XXX")`. I am not able create `@Injectable` for this resource (Missing `@Injectable` for field). This is the same problem like #359 . 
I think the solution for this problem is update method
https://github.com/jmockit/jmockit1/blob/f4d60f3c7a016babcd786c98d817c1ef5bb77c21/main/src/mockit/internal/injection/InjectionPoint.java#L76

and add conversion for "/" as delimiter.

**Comment by rliesenfeld** [comment]
The "/" character is supported in the `lookup` attribute of `@Resource`, but not in `name`. I am not sure if it's valid for `name` to have slashes in the Java EE spec, but it seems wrong since "abc/Xyz" is actually a hierarchy with two names, while "abc-Xyz" or "abc.Xyz" is still a single name.

Any reason why your Resources are using `name` instead of `lookup`, for such composite names?

**Comment by Saljack** [comment]
I think "/" is valid for name. For examle [EJB 3.0 and EJB 3.1 application bindings overview from IBM](https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/cejb_bindingsejbfp.html) contains examples where slash is used in `@EJB` name (`@EJB(name="ejb/FacadeRemoteRef")` ). I agree with hierarchy and two names and I think it is the right reason why we use slash in names. 
Solution should be use only the last name after slash. For example:
```
@Resource(name="abc/XYZ")
Resource resource;
```
and 
```
@Injectable
Resource XYZ
```

I don't want change `name` to `lookup` I don't see any reason to change it.

**Comment by rliesenfeld** [comment]
Ok. I settled on what's probably a better solution: to fall back on matching the annotated field name, when no injectable is found which matches the `name` or `lookup` attributes.
