### ISSUE TITLE
JMockit, Version 1.38, does not work with unnamed Verifications at all

### ISSUE THREAD

**Issue by jdsmithsos** [jmockit/jmockit1#535]
I went through an upgrade process to go from a much older version of JMockit, Version 1.25, to upgrade to Version 1.40.  I only got as far as Version 1.37.

During the process I made some changes, including converting all of the named Verifications and Expectations to use a method instead of extending Verifications and Expectations classes (per the Version 1.38 release notes).

But at Version 1.38, the Verifications stopped working completely.  

At Version 1.37 the new verification methods are being called, and the Verifications are successful.  At Version 1.38 the Verifications fail.

The weird thing is, the failure is only on the command line, but the Verifications are successful within Eclipse Neon.  Command line builds rule because of Jenkins CI.  It doesn't really matter what happens in Eclipse.  I even tried running >mvn eclipse:eclipse on the command line to update the Eclipse project files, to try to get Eclipse to fail, but it does not fail.

I am using Java version 1.8.0_121, Maven version 3.3.9.
JUnit version 4.12 (and I verified that the jmockit dependency is before junit in the pom.xml)
Maven Surefire plugin version 2.19.1.

**Comment by jdsmithsos** [comment]
I got a notice that this issue has been closed because it is not reproducible.  I figured out the issue and can reproduce it easily.

The problem starts with version 1.38, and is caused by the maven-surefire-plugin configuration.
This only happens on a command line build, it does not occur in Eclipse.

In the pom.xml, if the maven-surefire-plugin is specified, this problem occurs if there is a <configuration> section.  I saw the problem with using <includes> and <excludes>.

When I run maven-surefire-plugin with the following configuration, the Expectations and Verifications fail.

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.0</version>
    <configuration>
        <includes>
            <include>**/*Test*</include>
        </includes>
        <excludes>
            <exclude>**/*IT.java</exclude>
        </excludes>
    </configuration>
</plugin>

When I comment out or delete the <configuration>

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.0</version>

</plugin>

the Expectations and Verifications work again.

Or, it will work by adding the <forkCount> configuration:

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.0</version>
    <configuration>
        <forkCount>3</forkCount>
        <includes>
            <include>**/*Test*</include>
        </includes>
        <excludes>
            <exclude>**/*IT.java</exclude>
        </excludes>
    </configuration>
</plugin>

This is a known problem.  The forkCount solution I found by Goggle search.

**Comment by rliesenfeld** [comment]
Did you read this part in the new issue template?

"* Please avoid reporting a problem that cannot be reproduced by project members.
Instead, include enough information (typically, an example test or more, perhaps accompanied by a
Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments."

**Comment by rliesenfeld** [comment]
Reproduced it now: it's solely due to the use of "`<include>**/*Test*</include>`", which tells Surefire (on any version) to regard *all* classes with names containing "Test" as test classes. What the user probably doesn't realize is that this *also* includes classes that are *nested* inside a `*Test*` class. And then Surefire prematurely loads said classes (before any test is executed), preventing JMockit from properly processing any of the `Expectations` and `Verifications` subclasses found in tests.

I vaguely remember to have seen this before, but can't find any issue related to it.

Anyway, I don't see anything that can reasonably be done on JMockit's side to prevent this problem. The real cause is an erroneous Surefire configuration, since Surefire defaults ("Test*.java" and "*Test.java") work fine, with no need to specify "`*Test*`".

**Comment by jdsmithsos** [comment]
Even if the Surefire plugin configuration is the blame, I have been using that same configuration for over 2 years on my projects, and never had a problem with JMockit until version 1.38.  So something has changed in JMockit in 1.38 that exposed this problem.
