### ISSUE TITLE
Getting "Missing invocation to" exception even though getting the expected output

### ISSUE THREAD

**Issue by chjose** [jmockit/jmockit1#549]
Please provide the following information:

* Version of JMockit that was used: 1.38

* Description of the problem: Getting missing invocation error even though the invocations are happening as expected.

**Comment by chjose** [comment]
Here is the error log:

```
[junit] Missing invocation to:
    [junit] redshift.dao.MetricsFetchRedshiftDao#query("{<query map>}", CustomerIdMetricsExtractor@37313c65, "<id>")
```

Not pasting the entire trace as the code is proprietary. 

Found a workaround by adding _expected=Throwable.class_ to the test method signature.

**Comment by chjose** [comment]
Place of the error log: https://github.com/jmockit/jmockit1/blob/d6566589aaaa74eb227e0b1f8387b30d1030dc7b/main/src/mockit/internal/expectations/invocation/ExpectedInvocation.java#L247

**Comment by chjose** [comment]
@rliesenfeld may i know the reason why you tagged it invalid?

**Comment by rliesenfeld** [comment]
The reason should be clear from what the "new issue" template says:

" Please avoid reporting a problem that cannot be reproduced by project members.
Instead, include enough information (typically, an example test or more, perhaps accompanied by a
Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments."

**Comment by chjose** [comment]
Let me try to get an example with the error reproduced. Thanks for replying!
