### ISSUE TITLE
Using 1.42+ in IntelliJ question

### ISSUE THREAD

**Issue by akornev** [jmockit/jmockit1#568]
A couple of questions:
1) I understand JMockit runner was removed in 1.42, but I don't understand why. Could you please provide some details? I've seen people asking this very same question elsewhere in this repo, but I could not find any answer.

2) in #546, with respect to the now mandatory`-javaagent`, you state that 
> the IDE should automatically add it to the command line whenever a test is executed (with IntelliJ, which I use, it's working fine...)

Could you please clarify what you mean, because it doesn't? Do you run your unit tests using IntelliiJ's JUnit runner, or instead you delegate to maven? How do you run individual unit tests? Manually adding the `-javaagent:...` to the Run/Debug configuration for every test is not feasible. Please advise.

Also, since this project has no other active venue for asking questions (Google Groups one doesn't seem to be active), please do not close the ticket immediately after answering, just in case there may be any follow-up questions (or, feel free to propose moving the discussion to a different place).

Thanks!

**Comment by rliesenfeld** [comment]
Sure:
1. Since 1.42, the "-javaagent" parameter became mandatory, rendering the `JMockit` JUnit 4 runner redundant and useless.
2. I run tests both from IntelliJ and from Maven (Surefire). I run tests individually, single test class, etc.  all the time, from IntelliJ with the "Ctrl+Shift+F10" key combination, the menu items or toolbar buttons. In both cases, the -javaagent parameter is automatically added to the command line (assuming it is properly specified in the pom.xml file, of course). For a fully working example, see the `jmockit1/samples/petclinic` module in the github repository.

**Comment by akornev** [comment]
Wrt to `-javaagent`, I guess my question was why the parameter is now mandatory. Thanks!

**Comment by rliesenfeld** [comment]
The answer to that is supposed to be in #546.

**Comment by akornev** [comment]
Sorry for being obtuse, but in your comment in #546 it sounds like you're discussing

> several technical difficulties in getting dynamic Java agent loading

but to me the question really is why do you need to load the agent in the first place? I guess I'm missing some key points about how JMockit works internally. 

Thanks! Appreciate your patience!

**Comment by rliesenfeld** [comment]
Loading the Java agent is a requirement of the JVM, as the only way to obtain a `java.lang.instrument.Instrumentation` object (with which JMockit implements mocking & faking) is to have it passed to the `premain` or `agentmain` method (which are similar to the standard Java `main` method). Unfortunately, there is no `InstrumentionFactory` class in the Java SE APIs.
