### ISSUE TITLE
A static factory method for a @Mocked class returns null

### ISSUE THREAD

**Issue by industrious** [jmockit/jmockit1#570]
* Version of JMockit that was used: 

1.44 (Java version: 1.8.0_172)

* Description of the problem:

A static factory method for a @Mocked class returns null.
If I understand it right, this feature is advertised in 1.1 here https://jmockit.github.io/tutorial/Mocking.html#cascading

It seems like a regression which was working with JMockit 1.26 (the last version which it works with and which I could find is 1.27)

Attached: [serviceloadertest.zip](https://github.com/jmockit/jmockit1/files/2698995/serviceloadertest.zip)

**Comment by rliesenfeld** [comment]
Yes, since JMockit 1.28 most methods from `java.util` classes are excluded from cascaded mocking. This was done for safety and performance reasons.

Note there is no actual need to mock the `ServiceLoader` class in the example test, as the following version works (personally, I would never mock this class):

```
public class SampleTest {
    @Test
    public void testServiceLoader() {
        ServiceLoader<SampleService> l = ServiceLoader.load(SampleService.class);

        assertNotNull(l);
        assertNotNull(l.iterator());
    }
}
```
