### ISSUE TITLE
Question: Is mocking of subclasses of Throwable can be supported?  If not, can this be documented?

### ISSUE THREAD

**Issue by apogrebnyak** [jmockit/jmockit1#601]
Please provide the following information:

* Version of JMockit that was used: 
1.46

* Description of the problem:

In this comment https://github.com/jmockit/jmockit1/issues/437#issuecomment-320699909 you've said that non-mocking of subclasses of `Throwable` is feature, unless a legitimate need can be show.

I agree that for most of the standard exceptions, where public constructor exists, there is no need for mocking.

However there are many 3rd party libraries, especially database drivers, that have exception hierarchies that are themselves public, but do not have public constructors.

One reason for using a mocking library is to test the edge conditions when communicating with DB, and especially to see how the tested code reacts to different exceptions that the database driver may generate.  I think that the setup of such a test should be easy, and the ability to have an exception mocked is very beneficial in this case.

I also admit, that I may not fully understand why ability to mock exceptions may be detrimental to the framework.  If you could, can you explain why this would be the case?

Finally, if ability to mock derivatives of Throwable (as well as other handful of classes in `java.lang`) is not supported, could it be clearly documented in the Tutorial?

Thank you very much for extremely intuitive and productive library,

-Alex

P.S. Here is a link to my previous question -> https://github.com/jmockit/jmockit1/issues/600

**Comment by apogrebnyak** [comment]
I understand the reluctance to fully mock Throwable.

One suggestion may be to introduce a new mocking annotation (e.g. `@Stubbed`) that may be only accepted in `result` assignment.

**Comment by rliesenfeld** [comment]
I don't think that mocking `MongoWriteException` is a legitimate case. Instead, a *real* test should be written that manages to get a MongoDB server to throw the exception in a realistic situation. Wanting to use a mocking library to force it is a common sign, in my experience, of users that just want to get a test that runs and passes, rather than a proper & meaningful test that is actually worth having.

For that exception, I imagine trying to bulk store documents with a unique key violation should trigger it.
