### ISSUE TITLE
Mocking Private Methods

### ISSUE THREAD

**Issue by ramsahota** [jmockit/jmockit1#629]
* Version of JMockit that was used: 1.48

* Description of the problem or enhancement request: Since JMockit has deprecated Deencapsulation invoke method. How do you suggest mocking and testing private methods with newer releases of JMockit? Can this information be added to the Online tutorial section on what are the best practices for mocking private methods.

**Comment by rliesenfeld** [comment]
JMockit's [Release notes](http://jmockit.github.io/changes.html) page mentions the retirement of support for mocking/faking private methods (do a text search for "private"). That was made because mocking privates is commonly regarded as a bad practice, and there is no known legitimate use case for doing it, to the best of my knowledge.

As for *testing* private methods, the commonly accepted way to do it is by testing the public methods that call them. Generally, a proper test should never target implementation details.

The Tutorial already provides [some guidance](http://jmockit.github.io/tutorial/Introduction.html#isolation), but the problem is, most users won't ever read it, or won't pay much attention to it.

**Comment by TheGoesen** [comment]
Well here's one simpliefied usecase why I really want and need mocking of private methods.
Supposed legacy code 

```
class Input{
private File file;
public File getFile(){
    return file;
}
}
class Reader{
void read(Input input){
    var stream= new FileInputstream(input.getFile());
    //do whatevever with your stream
}
}
```

ugly but works and hurra `getFile` is mockable. Now i do a little refactoring. Note that everything should work exactly like before for a given file. And I have tests in place to verify that.


```
class Input{
private File file;

public InputStream getData(){
   return new FileInputstream(getFile());
}

private File getFile(){
    return file;
} 
}
// appropriate changes to Reader as well
```
But Jmockit will shoot me. Not because I have changed the behavior of the application, but because i fixed a design error and made a method private that should have been private in the first place. I could remove the braking tests and replace them with different ones. But the entire point of testing is to verify that the application is still behaving the way it should or used to. Which it totally still does. I think... no real way to tell.

So in praxis the effect of not allowing mocking of private methods are:

-  Developers are refusing (or at least lacking euphory) to refactor of even fix bugs in their code because it would costs too much ressources to tackle the test cases as w.
- Testcases are deleted with no replacement more frequently. ('You used to be able to test this, but no longer')
- Developers who attempt neccessary refactorings to a given application will advance more slowly
- Most people will simply change the visibility of the things they want to mock. Here: we can make/keep getFile public. Nobody will notice. And if someobdy notices theres nothing he can do without breaking the tests and getting stuck in refactoring hell.
- Or adding unneccessary hooks that seem to be valid usescases but in reality you only need to support them for testing code. Here: add a method 'setFile'. Might be needed anyway depending on your application. Probably not.
- Or they just punch a huge  hole through everything and add a comment. 'Do not call, for testing only'.  
Theres even an annotation to support that kind of behaviour...
http://javadox.com/org.jetbrains/annotations/13.0/org/jetbrains/annotations/TestOnly.html

I think thats the main reason why you need mocking of private methods as a professional developer. Also educating people to write better test cases by removing functionality? It's not as easy as that.

**Comment by TheGoesen** [comment]
so while mocking private _behaviour_ is bad (But still better than no tests at all...maybe ?), I don't see anything wrong with patching a  configuration or a ressource that is stored in a field or method that just happen to be  private.
