### ISSUE TITLE
Running under Maven/Intellij

### ISSUE THREAD

**Issue by mgrand** [jmockit/jmockit1#648]
Please provide the following information:

* Version of JMockit that was used: 1.48

* Description of the problem or enhancement request:
I am running under Windows. When I specify the java agent as documented
```
                    <argLine>
                        -javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
                    </argLine>
```
It works perfectly when I run tests with maven. 

When I try to run tests under Intellij, it fails because the agent cannot be found. The problem is that there is a space character in the name of my home directory "Mark Grand". Intellij creates the command line without accounting for this so that the path of the agent appears to end in the middle of my home directory name.

A good work-around that I have found is to add double-quotes to the path like this:
```
                    <argLine>
                        -javaagent:"${settings.localRepository}"/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar
                    </argLine>
```

I suggest that you modify your documentation to include the double quotes or a least note this work-around.

**Comment by lawrencexu** [comment]
@mgrand 
I have tried the same workaround. 
But we have used Jacoco for test coverage so there is extra setting in the argLine that will fail the workaround because of the nested double-quotes.
I have experimented a lot, the final solution is add extra check in maven-enforcer-plugin to fail maven build if there is any space character in _${settings.localRepository}_ and tell project developer to move local maven repository to a file path without space character and change the _localRepository_ in _.m2/settings.xml_.

**Comment by rliesenfeld** [comment]
Documentation updated.
