### ISSUE TITLE
Since 1.48 selective partial mocking of constructors is no longer possible.

### ISSUE THREAD

**Issue by cranphin** [jmockit/jmockit1#649]
Please provide the following information:

* Version of JMockit that was used: 1.48/1.49

* Description of the problem or enhancement request:
Since 1.48 selective partial mocking of constructors is no longer possible.

The following change was added in 1.48:

> Dropped support for the partial mocking of classes through new Expectations(ToBeMocked.class) {...}. This constructor can still be used for the partial mocking of instances, though. If a class needs to have only some constructors and/or static methods mocked, the use of a MockUp is the recommended alternative.

Because of this, an expectation like the following is no longer possible:
```
static final File LOG1 = new File("mylog.txt");
@Injectable FileInputStream fileInputStream;
...
        new Expectations(FileInputStream.class) {{
                new FileInputStream(LOG1);
                result = fileInputStream;
                minTimes = 1;

                fileInputStream.read((byte[]) any, anyInt, anyInt);
                result = new IOException("Test exception");
                minTimes = 1;
            }};
```
The main intent of this example is mocking only a single FileInputStream instance, since the JVM and support libraries will also use FileInputStream, which should not be mocked.

I don't see a way to get the same results using the suggested alternative 'MockUp'.

I'm looking for a way to get similar behaviour, mock only a specific instance of FileInputStream (one created with a specific File).

**Comment by rliesenfeld** [comment]
It's indeed doable with a `MockUp`, though uglier than the (already ugly) `@Injectable+Expectations` version:
```
package otherTests;

import mockit.*;
import org.junit.*;
import org.junit.rules.*;

import java.io.*;

public class ExampleBadTest {
    @Rule public TemporaryFolder temporaryFolder = new TemporaryFolder();

    @Test
    public void mockSingleFutureInstanceOfAClass() throws Exception {
        File testFile = temporaryFolder.newFile("anotherFile.txt");

        new MockUp<FileInputStream>() {
            FileInputStream targetInstance;

            @Mock
            void $init(Invocation inv, File file) {
                if (isTargetFile(file)) {
                    targetInstance = inv.getInvokedInstance();
                    return;
                }

                inv.proceed();
            }

            private boolean isTargetFile(File file) {return "mylog.txt".equals(file.getName()); }

            @Mock
            int read(Invocation inv, byte[] buf, int off, int len) throws IOException {
                if (inv.getInvokedInstance() == targetInstance) {
                    throw new IOException("Test exception");
                }

                return inv.proceed();
            }
        };

        // The following is assumed to be from the code under test:
        FileInputStream logFile = new FileInputStream(new File("mylog.txt"));
        byte[] bytes = new byte[1024];

        try {
            logFile.read(bytes, 0, bytes.length);
        }
        catch (IOException e) {
            System.out.println("Failed to read log file: " + e.getMessage());
        }

        FileInputStream anotherFile = new FileInputStream(testFile);
        int r = anotherFile.read(bytes, 0, bytes.length);
        System.out.println("read bytes: " + r);
    }
}
```
This test does pass when executed, printing the following:
```
Failed to read log file: Test exception
read bytes: -1
```

However, I don't think we have a valid use case here. Writing a test for code that merely handles an `IOException` has two big problems: 1) it's essentially useless since the `FileInputStream#read` methods are *not* going to fail in practice, and the catch block is basically just to avoid having to propagate a checked exception out the log reading mehod; and 2) the test is strongly coupled to implementation details (consider someone could rewrite the CUT using one of several other Java IO APIs, such as the `Files` and `Path` classes, breaking the test without having changed the functionality) .

So, my suggestion: simply don't bother with such a test. Instead, test *real* and relevant functionality of your program, and avoid tight coupling from tests to implementation details.
