### ISSUE TITLE
[Question] After update from 1.22 to 1.48 some Expecatations result don't work

### ISSUE THREAD

**Issue by thiagofabre** [jmockit/jmockit1#699]
**Jmockit Version: 1.49**

In version 1.22 this Expectations was working fine:
```
    private void mockPulseCreateTest() {
        new Expectations() {{
            pulse.createTargetTest((SelfServiceRuleTestConfiguration) any, (SelfServiceRuleTestContext) any);
            result = createTargetTestResponse();
        }};
    }

```

But, after I updated to 1.49, the `result` was not working. So, I made a simple change to create the object before the Expectations block and now its working:
```
    private void mockPulseCreateTest() {
        final Map<String, Object> response = createTargetTestResponse();
        new Expectations() {{
            pulse.createTargetTest((SelfServiceRuleTestConfiguration) any, (SelfServiceRuleTestContext) any);
            result = response;
        }};
    }
```

I didn't understand the reason for the problem. Does anyone have an idea?

ps: The method `createTargetTestResponse` is just building a HashMap

**Comment by rliesenfeld** [comment]
It's not working how exactly? Do you get an error message? What does it say?

**Comment by rliesenfeld** [comment]
Anyway, the call to `createTargetTestResponse()` certainly should not be made from inside an expectation recording block, because it could easily happen to invoke some mocked method/constructor, which would lead to a very obscure test failure (or worse, a passing test which inadvertenly recorded undesired expectations).
